import { CustomerOrderForm } from "@/@types";
import { toast } from "react-toastify";

export const mapCustomerOrderToModel = (
  formData: CustomerOrderForm
): FormData => {
  const fd = new FormData();
  console.log("hhh", formData.regularFiles);
  // Append files if they exist
  if (formData.customFiles) {
    fd.append("file", formData.customFiles);
  }
  if (formData.regularFiles) {
    fd.append("ref", formData.regularFiles);
  }

  const today = new Date();
  const orderType = formData.customized ? "Custom" : "Regular";
  const deliveryType = formData.isGift
    ? "Gift"
    : formData.isDelivery
    ? "Delivery"
    : "Regular";

  // Add-on calculation
  if (Array.isArray(formData.addOn) && formData.addOn.length) {
    formData.addOn.forEach((item, idx) => {
      fd.append(`addOn[${idx}][name]`, item.name);
      fd.append(`addOn[${idx}][price]`, Number(item.price || 0).toString());
    });
  }
  // shipping
  fd.append("shipping[cost]", formData.shipping.cost.toString());
  fd.append("shipping[area]", formData.shipping.area);
  if (formData.deliveryCharge) {
    fd.append("deliveryFee", formData.deliveryCharge.toString());
  }

  // coupon
  if (formData?.coupon) {
    fd.append("coupon[code]", formData.coupon?.code);
    fd.append("coupon[discount]", formData.coupon.discount.toString());
    if (formData.couponAmount)
      fd.append("couponAmount", formData.couponAmount.toString());
  }

  // addon price & falvor price
  if (formData.addonPrice) {
    fd.append("addonPrice", formData.addonPrice.toString());
  }
  if (formData.flavorPrice) {
    fd.append("flavorPrice", formData.flavorPrice.toString());
  }
  // Basic order info
  fd.append("orderType", orderType);
  fd.append("deliveryType", deliveryType);
  fd.append("orderDate", today.toISOString());
  fd.append("orderId", "customer"); // Will be auto-generated by backend

  // Customer Info
  fd.append("customerInfo[name]", formData.customer.name);
  fd.append("customerInfo[email]", formData.customer.email);
  fd.append("customerInfo[phone]", formData.customer.phone);
  fd.append("customerInfo[street]", formData.customer.street || "");
  fd.append("customerInfo[city]", formData.customer.city);
  fd.append("customerInfo[zip]", formData.customer.zip);
  fd.append("customerInfo[location]", formData.customer.address);

  // Delivery Address
  fd.append(
    "deliveryInfo[deliveryAddress][street]",
    formData.isGift || formData.isDelivery
      ? formData.delivery?.street || ""
      : formData.customer.street || ""
  );
  fd.append(
    "deliveryInfo[deliveryAddress][city]",
    formData.isGift || formData.isDelivery
      ? formData.delivery?.city || ""
      : formData.customer.city
  );
  fd.append(
    "deliveryInfo[deliveryAddress][zip]",
    formData.isGift || formData.isDelivery
      ? formData.delivery?.zip || ""
      : formData.customer.zip
  );
  fd.append(
    "deliveryInfo[deliveryAddress][location]",
    formData.isGift || formData.isDelivery
      ? formData.delivery?.address || ""
      : formData.customer.address
  );

  // Gift recipient info if applicable
  if (formData.isGift) {
    fd.append("deliveryInfo[giftTo][customerId]", "gift-recipient");
    fd.append("deliveryInfo[giftTo][name]", formData.nameGift || "");
    fd.append("deliveryInfo[giftTo][phone]", formData.phoneGift || "");
    fd.append("deliveryInfo[giftTo][street]", formData.delivery?.street || "");
    fd.append("deliveryInfo[giftTo][city]", formData.delivery?.city || "");
    fd.append("deliveryInfo[giftTo][zip]", formData.delivery?.zip || "");
  }

  // Cake info
  if (formData.customized && formData.customizedCakeDetails) {
    fd.append("customInfo[name]", formData.customizedCakeDetails.cakeName);
    fd.append(
      "customInfo[servingSize]",
      formData.customizedCakeDetails.cakeWeight
    );
    fd.append(
      "customInfo[flavor]",
      formData.customizedCakeDetails.flavor
    );

    fd.append(
      "customInfo[description]",
      `${formData.customizedCakeDetails.description} <br/> Shape:${formData.customizedCakeDetails.shape} <br/> Layer: ${formData.customizedCakeDetails.layers}`
    );
    fd.append(
      "customInfo[estimatePrice]",
      Number(formData.customizedCakeDetails.price).toString()
    );
    fd.append("customInfo[quantity]", "1");
  } else {
    if (!formData.cakeId || formData.cakeId === "") {
      toast.error("Cake Id Missing");
    }
    fd.append("cakeInfo[id]", formData.cakeId || "");
    fd.append("cakeInfo[name]", formData.title || "");
    fd.append("cakeInfo[servingSize]", formData.weight || "");
    fd.append("cakeInfo[category]", formData.category || "");
    fd.append(
      "cakeInfo[discountAmount]",
      Number(formData.discountAmount).toString()
    );
    fd.append("cakeInfo[sizePrice]", Number(formData.sizePrice).toString());
    fd.append("cakeInfo[cakePrice]", Number(formData.cakePrice).toString());
    fd.append("cakeInfo[message]", formData.message || "");
    fd.append("cakeInfo[note]", formData.note || "");
    fd.append("cakeInfo[flavor][name]", formData.flavor);
    fd.append(
      "cakeInfo[flavor][price]",
      Number(formData.flavorPrice).toString()
    );
  }

  // Payment info
  if (orderType === "Custom" && formData.customizedCakeDetails) {
    fd.append(
      "paymentInfo[orderAmount]",
      Number(formData.customizedCakeDetails.price).toString()
    );
  } else {
    fd.append(
      "paymentInfo[orderAmount]",
      Number(formData.finalPrice).toString()
    );
  }

  if (formData.paymentType === "partial") {
    fd.append(
      "paymentInfo[paymentAmount]",
      Number(formData.partialPaymentAmount || 0).toString()
    );
  } else if (formData.paymentType === "Unpaid") {
    fd.append("paymentInfo[paymentAmount]", "0");
  } else {
    const fallbackPrice =
      Number(formData.finalPrice) ||
      Number(formData.customizedCakeDetails?.price) ||
      0;

    fd.append("paymentInfo[paymentAmount]", fallbackPrice.toString());
  }

  // Delivery info
  fd.append("deliveryInfo[deliveryDate]", formData.deliveryDate.toISOString());
  fd.append("deliveryInfo[deliveryTime]", formData.deliveryTime);
  fd.append("deliveryInfo[deliveryNotes]", formData.deliveryNote || "");

  // Status info
  fd.append(
    "paymentStatus",
    formData.paymentType === "Unpaid" ? "Unpaid" : "Full-Paid"
  );
  fd.append("paymentMethod", formData.paymentMethod);
  fd.append("orderStatus", "Pending");
  fd.append("deliveryStatus", "Waiting");

  return fd;
};
